-- =====================================================
-- Retail Revenue Analysis
-- Business-focused SQL queries used for insights and dashboard
-- =====================================================


-- 1. Total revenue generated after applying discounts
SELECT
    SUM(p.price * o.quantity - o.discount) AS total_revenue
FROM orders o
JOIN products p 
    ON o.product_id = p.product_id;


-- 2. Total revenue without considering discounts
SELECT
    SUM(p.price * o.quantity) AS revenue_without_discount
FROM orders o
JOIN products p 
    ON o.product_id = p.product_id;


-- 3. Revenue generated by each city (descending order)
SELECT
    c.city,
    SUM(p.price * o.quantity - o.discount) AS city_revenue
FROM orders o
JOIN customers c 
    ON o.customer_id = c.customer_id
JOIN products p 
    ON o.product_id = p.product_id
GROUP BY c.city
ORDER BY city_revenue DESC;


-- 4. Revenue generated by each customer (descending order)
SELECT
    c.customer_name,
    SUM(p.price * o.quantity - o.discount) AS customer_revenue
FROM orders o
JOIN customers c 
    ON o.customer_id = c.customer_id
JOIN products p 
    ON o.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY customer_revenue DESC;


-- 5. Customer segmentation based on total revenue contribution
SELECT
    c.customer_name,
    SUM(p.price * o.quantity - o.discount) AS total_revenue,
    CASE
        WHEN SUM(p.price * o.quantity - o.discount) >= 1000 THEN 'High Value'
        WHEN SUM(p.price * o.quantity - o.discount) >= 500 THEN 'Mid Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM orders o
JOIN customers c 
    ON o.customer_id = c.customer_id
JOIN products p 
    ON o.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_revenue DESC;


-- 6. Count of customers in each revenue segment
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT
        c.customer_name,
        SUM(p.price * o.quantity - o.discount) AS total_revenue,
        CASE
            WHEN SUM(p.price * o.quantity - o.discount) >= 1000 THEN 'High Value'
            WHEN SUM(p.price * o.quantity - o.discount) >= 500 THEN 'Mid Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM orders o
    JOIN customers c 
        ON o.customer_id = c.customer_id
    JOIN products p 
        ON o.product_id = p.product_id
    GROUP BY c.customer_name
) t
GROUP BY customer_segment;


-- 7. Monthly revenue trend
SELECT
    MONTHNAME(o.order_date) AS month,
    SUM(p.price * o.quantity - o.discount) AS monthly_revenue
FROM orders o
JOIN products p 
    ON o.product_id = p.product_id
GROUP BY MONTH(o.order_date), MONTHNAME(o.order_date)
ORDER BY MONTH(o.order_date);


-- 8. Identify inactive (churned) customers
SELECT
    customer_id,
    customer_name,
    city,
    signup_date
FROM customers
WHERE is_active = 0;


-- 9. Revenue generated by inactive (churned) customers
SELECT
    SUM(p.price * o.quantity - o.discount) AS churned_customer_revenue
FROM orders o
JOIN customers c 
    ON o.customer_id = c.customer_id
JOIN products p 
    ON o.product_id = p.product_id
WHERE c.is_active = 0;
